Released first task
AS2/adv_cg_polytech pull request #1
Opened 2024-02-21 10:34 UTC by AS2

Implemented:
- rotating cube with camera;
- checked all HRESULT;
- activated debug layers, shaders debugging and RenderDoc marks for _DEBUG build.

2024-02-22 11:34 UTC, anthark requested changes
ОК, но строковые константы для маркеров нужно поправить

2024-02-22 11:34 UTC, anthark commented on cg_labs/t1_debugger/renderer.cpp
> +  pAnnotation->BeginEvent((LPCWSTR)("Clear background"));
Это вы как-то слишком смело поступили здесь =) const char* привели к const wchar_t* =)

Надо, чтобы строковая константа была сразу Уникодной: L"Clear background", а то будет как на картинке

![изображение](https://github.com/AS2/adv_cg_polytech/assets/14963654/de6e0c6c-4007-4342-abdc-d6931928ff8b)

2024-02-22 12:36 UTC, AS2 commented on cg_labs/t1_debugger/renderer.cpp
> +  pAnnotation->BeginEvent((LPCWSTR)("Clear background"));
ой, упс, и правда, не заметил даже. Поправил!

2024-02-25 10:25 UTC, anthark approved these changes
Всё, теперь всё ОК - засчитано

2024-02-25 10:25 UTC, merged